package com.onmobile.rbt.baseline.http.api_action.errormodule;

public enum ErrorSubCode {
    //RBT ERROR SUB_CODE
    CONNECTION_ERROR, NA, SUBDOESNTEXIST, INTERNAL_SERVER_ERROR, SONGNOTFOUND, SONGEXPIRED, CATEGORYDOESNTEXIST, CONTENTEXPIRED, SUBALREADYOWNSCONTENT, OPERATION_NOT_ALLOWED, INVALIDPARAMETER, DEACTIVATE_SELECTION_ERROR, UNKNOWNERROR, INVALIDSHUFFLELISTID, UDPISACTIVE, SUBDOESNTOWNCONTENT, SUBACTPENDING, INVALIDSUBSCRIBERID, OFFERNOTFOUND, SUBALREADYEXIST, SUBSTATUSCHANGENOTALLOWED, SUBDEACTPENDING, SUBSCRIBERGRACE, SUBSCRIBERSUSPENDED, PLAYRULENOTEXIST, LOCKED_USER, CONTENT_BLOCKED_LITE_USER, CONTENT_BLOCKED_ADRBT, CONTENT_BLOCKED_PROFILE, CONTENT_BLOCKED_CORP_USER, INVALID_SUBSCRIBER_STATE, CORPORATE_CONTENT_NOT_ALLOWED, DOWNLOAD_MONTHLY_LIMIT_REACHED, BLOCK_LAST_SONG_DELETION, UNKNOWN, GENERAL_ERROR, MAX_UDP_LIMIT_REACHED, MAX_UDP_CONTENT_LIMIT_REACHED,
    DOWNLOADS_OVERLIMIT,
    //Referal Error Code Add Child
    PARENT_NOT_FOUND, INTERNAL_ERROR, CHILD_ALREADY_ADDED, CHILD_ALREADY_ADDED_DIFF_PARENT, CHILD_ACTIVE, CHILD_INVALID, CHILD_ALREADY_REGISTER_AS_PARENT,

    //Refereal Error Code for Remove Child
    CHILD_ALREADY_REMOVED, CHILD_LIMIT_EXCEEDED, CHILD_ALREADY_ADDED_WITH_DIFFERENT_PARENT, OPERATOR_NOT_SUPPORTED, GIFT_EXPIRED, BILLING_TYPES_NOT_AVAILABLE, WALLET_PENDING;

    public static String CONNECTION_ERROR_DESC = "Network error. Please try again.";

    public static String GENERAL_ERROR_DESC = "Some error occurred. Please try again after some time. If problem persists contact our Customer Care Service.";
}
